security:
    erase_credentials: false
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        AcmeBundle\Acme\User\LdapUser: plaintext
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
#        in_memory: { memory: ~ }
#        my_ldap:
#            ldap:
#                service: Symfony\Component\Ldap\Ldap
#                base_dn: '%env(LDAP_USERS_DN)%'
#                search_dn: '%env(LDAP_USER)%'
#                search_password: '%env(LDAP_PASSWORD)%'
#                default_roles: ROLE_USER
        chain_provider:
            chain:
               providers: [fos_userbundle, fr3d_ldapbundle]
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username
#        fos_userbundle:
#            id: fos_user.user_provider.username
#        chain_provider:
#            chain:
#                providers: [my_ldap, fos_userbundle]            
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: chain_provider
            fr3d_ldap:  ~
            form_login:
                provider: chain_provider
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: true
                login_path: fos_user_security_login
                default_target_path: home
            logout_on_user_change: true
            logout:     true
            anonymous:  true

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: /api/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/build/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/, roles: ROLE_USER }
