sms_service:
    provider: '%env(SMS_PROVIDER)%' # Acumbamail o Dinahosting
    test: '%env(bool:SMS_TEST)%'
    providers:
        dinahosting: 
            username: '%env(SMS_USERNAME)%'
            password: '%env(SMS_PASSWORD)%'
            account: '%env(SMS_ACCOUNT)%'
            sender: 'AMOREBIETA'
        acumbamail:
            authToken: '%env(SMS_ACUMBAMAIL_AUTHTOKEN)%'
            version: 1
            timeout: 20.0
            sender: 'AMOREBIETA'
            countryCode: '34'
